### ISSUE TITLE
Wrong password to CAS-PEAL

### ISSUE THREAD

**Issue by anton-eug** [LIUYOU2015/LIUYOU2015.github.io#1]
Hello, you posted a link to download the CAS-PEAL database, but the password for the archive `ax4S)*Arj;Bg”XkL9Mva%-2K` does not work. Please can you provide a valid password.

**Comment by LIUYOU2015** [comment]
I'm sorry to hear about that, try this again `ax4S)*Arj;Bg"XkL9Mva%-2K`. The wrong password was using '“', which is in Chinese form. 
Please read [http://www.jdl.ac.cn/peal/index.html](http://www.jdl.ac.cn/peal/index.html) Request page. I strongly recommend you complete this form [https://www.sojump.hk/jq/10670671.aspx](https://www.sojump.hk/jq/10670671.aspx). I should not have disclose the database. 

> The CAS-PEAL-R1 face database is released to universities and research institutes for research purpose only. To request a copy of the CAS-PEAL-R1 face database, please do as follows: 
> 
> (1) Download the CAS-PEAL face database Release Agreement, read it carefully. Before using the database, you are recommended to refer to the paper “Wen Gao, Bo Cao, Shiguang Shan, Xilin Chen, Delong Zhou, Xiaohua Zhang, Debin Zhao. The CAS-PEAL Large-Scale Chinese Face Database and Baseline Evaluations. IEEE Trans. on System Man, and Cybernetics (Part A), vol.38, no.1, pp149-161. 2008.1”. You might also be interested in other papers we have published on face recognition by visiting here.
> 
> (2) Complete the application form online at https://www.sojump.hk/jq/10670671.aspx . Then you will be informed how to download the database.

**Comment by anton-eug** [comment]
> Please read http://www.jdl.ac.cn/peal/index.html Request page. I strongly recommend you complete this form https://www.sojump.hk/jq/10670671.aspx. I should not have disclose the database.

Ok i will fill out the form, but password worked.
